# Welcome to Jekyll!
#
# Site settings
# Personalize your new site. Variables like {{ site.title }}, {{ site.email }},
# and others will be available throughout your templates.

#title: eiplgrader
#make title an image
title: EiplGrader Documentation
logo: "/assets/images/eiplgrader.png"
email: dhsmith2@illinois.edu
description: >- # Ignore newlines until "baseurl:"
  An AI-powered autograder for "Explain in Plain Language" questions in computer science education. Providing immediate, accurate feedback on natural language descriptions of algorithms and concepts.
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Build settings
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs@v0.3.3
search_enabled: true
heading_anchors: true
color_scheme: "dark"

# Navigation
nav_sort: case_sensitive

aux_links:
  GitHub: 'https://github.com/CoffeePoweredComputers/eiplgrader'
  PyPI: 'https://pypi.org/project/eiplgrader/'
  David H Smith IV: 'https://hamiltonfour.tech'

footer_content: "Copyright © 2023-2025 eiplgrader. Powered by Jekyll and just-the-docs theme."

# Just the Docs configuration
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hamiltonfour/eiplgrader"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Google Analytics
# ga_tracking: UA-XXXXXXXXX-X
# ga_tracking_anonymize_ip: true

# Exclude these files and directories from the site build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

