# Welcome to Jekyll!
#
# Site settings
# Personalize your new site. Variables like {{ site.title }}, {{ site.email }},
# and others will be available throughout your templates.

#title: eiplgrader
#make title an image
title: eiplgrader
logo: "/assets/images/eiplgrader.png"
email: dhsmith2@illinois.edu
description: >- # Ignore newlines until "baseurl:"
  An AI-powered autograder for "Explain in Plain Language" questions in computer science education. Providing immediate, accurate feedback on natural language descriptions of algorithms and concepts.
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Build settings
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs@v0.3.3
search_enabled: true
heading_anchors: true
color_scheme: "dark"

aux_links:
  GitHub: 'https://github.com/CoffeePoweredComputers/eiplgrader'
  David H Smith IV: 'https://hamiltonfour.tech'

footer_content: "Copyright © 2023-2025 eiplgrader. Powered by Jekyll and just-the-docs theme."

# Exclude these files and directories from the site build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
