name: Test Suite

on:
  push:
    branches: [ '*' ]  # Run on all branches
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          pyproject.toml
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black pylint mypy types-requests
    
    - name: Lint with pylint
      run: |
        pylint --disable=C0111,C0103,C0114,C0115,C0116,E0401,R0913,R0917,R0914,C0301,C0304,W0611,W0612,W0613,W0718 eiplgrader/* tests/
    
    - name: Check code formatting with black
      run: |
        black --check eiplgrader/ tests/
    
    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports eiplgrader/
    
    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v --tb=short --cov=eiplgrader --cov-report=xml --cov-report=term
        echo "### Unit Test Results 🧪" >> $GITHUB_STEP_SUMMARY
        echo "✓ Unit tests completed for Python ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
      
    - name: Run integration tests
      run: |
        python -m pytest tests/integration/ -v --tb=short --cov=eiplgrader --cov-append --cov-report=xml --cov-report=term
        echo "✓ Integration tests completed for Python ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
      
    - name: Run edge case tests
      run: |
        python -m pytest tests/edge_cases/ -v --tb=short --cov=eiplgrader --cov-append --cov-report=xml --cov-report=term
        echo "✓ Edge case tests completed for Python ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
        echo "### All tests completed successfully! ✅" >> $GITHUB_STEP_SUMMARY
    
    - name: Upload coverage reports
      if: matrix.python-version == '3.11'  # Only upload once
      uses: codecov/codecov-action@v4
      continue-on-error: true
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
